---
site:
  title: "Introduction to image mode for Red Hat Enterprise Linux"
  url: https://github.com/rhpds/showroom_template_zero
  start_page: modules::01-create-an-image.adoc

content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-one-2025/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
