= Building policy into a bootc image

We could add all of these various configuration changes directly to our Containerfile and achieve compliance.  But, much like a package mode RHEL host, we can leverage automation to get the bulk of the work done, using Policies. 

First, go back into your Containerfile, and delete the two lines we added to install and enable FAPolicyd. 

Delete these:
....
RUN dnf -y install fapolicyd

RUN systemctl enable fapolicyd
....

Now, to setup our openscap policy, we will first make a change to the policy using autotailor. In our case, this is so that we do not break our lab environment, but in the real world this is very relevant, as you will likely need to tailor any compliance policy to your organization's needs.  In our case we are simply turning root logins back on. 

To do this, we will tailor our policy right on our build host.  The autotailor command comes from the openscap-utils package, and requires that the scap-security-guide is also installed.  We have done this for you in the lab environment.  

On your build host, Run the following:

[source,bash,role="execute",subs=attributes+]
----
autotailor --unselect xccdf_org.ssgproject.content_rule_sshd_disable_root_login --new-profile-id cis_server_l1_customized --output cis_server_l1_customized.xml /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml cis_server_l1 
----

Then we'll add the following lines to our Containerfile where we removed the FAPolicyd install and enable. Notice that the cis_server_l1_customized.xml file that we generated with autotailor is used here.  This file will contain your modified policy, and can be re-used on other build that you would like to apply the same custom policy to. 

[source,bash,role="execute",subs=attributes+]
----
ENV profileID=cis_server_l1_customized

COPY $profileID.xml /tmp/$profileID.xml
RUN oscap-im --profile $profileID --tailoring-file /tmp/$profileID.xml /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
----

With that in place, we can build our bootc image again. 

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----
As the bootc image buyilds, you will see output similar to this as the openscap profile is getting applied to the image. 
....
xccdf_org.ssgproject.content_rule_package_aide_installed:pass
xccdf_org.ssgproject.content_rule_aide_build_database:fail
xccdf_org.ssgproject.content_rule_aide_check_audit_tools:fail
xccdf_org.ssgproject.content_rule_aide_periodic_cron_checking:fail
xccdf_org.ssgproject.content_rule_configure_crypto_policy:pass
xccdf_org.ssgproject.content_rule_configure_ssh_crypto_policy:pass
xccdf_org.ssgproject.content_rule_partition_for_dev_shm:notapplicable
xccdf_org.ssgproject.content_rule_partition_for_tmp:notapplicable
xccdf_org.ssgproject.content_rule_dconf_db_up_to_date:notapplicable
....

After it completes, push the new image.

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

Now, on our vm, we can update, and apply the new image. 

[source,bash,role="execute",subs=attributes+]
----
sudo bootc update --apply
----

After the reboot, we can validate that our system has had the policy applied, by checking the compliance score via openscap. 

[source,bash,role="execute",subs=attributes+]
----
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_server_l1 --results ./results  /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
----
[source,bash,role="execute",subs=attributes+]
----
grep score results
----
You should see a score in the 90's like the output below:
....
    <score system="urn:xccdf:scoring:default" maximum="100.000000">92.530121</score>
....