= Security and Compliance in an Image Mode world.

Building and deploying using Image Mode has some built-in benefits from a security and compliance perspective.  
First, systems deployed with Image Mode are more likely to be built to your desired specifications, and second it is much easier to make sure that they stay that way.  
In the next few modules we'll walk through how to add security and compliance into your build, and also how to apply that policy using automation.  
We will also touch a bit on drift and getting your systems back into compliance after an event.

[NOTE] 
====
Because we will be making significant changes to our system, we are going to start fresh.  First we will build an updated bootc image, and then we will build a new guest vm just like we did at the beginning of the lab.
====

== Adding security controls to your image: FAPolicyd

One of the common services the security team uses to meet compliance and security mandteas is FAPolicyD.
The File Access Policy Daemon is a service that implements application allow-listing.  So let's see what it looks like to simply add it to our `Containerfile`.  

NOTE: We will be adding these changes after the `systemctl mask` line at the end of the exsting file

FAPolicyD is one of the standard tools the security team asked for, including the audit subsystem and SELinux troubleshooting. We'll also install the packages for the SCAP policy tools now since we know that's coming.
[source,dockerfile,role="execute",subs=attributes+]
----
# Security and Hardening 
RUN dnf -y install audit fapolicyd openscap-utils scap-security-guide setroubleshoot-server

RUN systemctl enable fapolicyd
----

Notice the only thing that needs to be defined to get FAPolicyD running at boot is a standard `systemctl` call.
Since we are targeting full RHEL systems and not containers, systemd is always running and available post-install so there's no need for any additional `init` environments or `ENTRYPOINT` definitions.
 

== Build the image and VM

Build the image so we can deploy our new VM and see if FAPolicyD is working.

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----

Now, we can build a new disk image, and start our new VM. 

[source,bash,role="execute",subs=attributes+]
----
podman run --rm --privileged --security-opt label=type:unconfined_t \
  --volume ./config.toml:/config.toml \
  --volume /var/lib/containers/storage:/var/lib/containers/storage \
  --volume .:/output \
  registry.redhat.io/rhel10/bootc-image-builder:10.1 \
  --type qcow2 \
  registry-{guid}.{domain}/base
----

Now let's copy that disk image to the proper location.  
[source,bash,role="execute",subs=attributes+]
----
cp -f qcow2/disk.qcow2 /var/lib/libvirt/images/security-vm.qcow2
----

Now we can build that the same way we created the Ops VM.

[source,bash,role="execute",subs=attributes+]
----
virt-install --name security-vm \
  --disk /var/lib/libvirt/images/security-vm.qcow2 \
  --import \
  --memory 4096 \
  --graphics none \
  --osinfo rhel10-unknown \
  --noautoconsole \
  --noreboot
----

After that completes, you will need to start up securty-vm, and then you will find the new system in the Sec SSH session tab.

[source,bash,role="execute",subs=attributes+]
----
virsh start security-vm
----

== Testing FAPolicyd
==== _Click on the tab labeled "Sec SSH session"_ 

Our goal here was to deploy fapolicyd, so now that we have, let's see if its working. 

The File Access Policy daemon's job is to prevent you from running unapproved applications.  Out of the box, it does this using a relatively simple application allow-list that has known trusted paths for installed binaries.  
[source,bash,role="execute",subs=attributes+]
----
sudo fapolicyd-cli -l
----

Since the system software deployed on an image mode host is part of a read-only filesystem, we can't simply overwrite a binary with a trusted path.
To test whether it's working, we can just take a known good binary, and put it somewhere odd, and then try to run it. 

[source,bash,role="execute",subs=attributes+]
----
cp /bin/ls ~
----

You should not be allowed to run `ls` from your home directorn. 
[source,bash,role="execute",subs=attributes+]
----
~/ls
----
....
-bash: /home/core/ls: Operation not permitted
....

Great! FAPolicyd works!  
But, we're nowhere close to satifying the security teams requirements, for that we'll need to do more than just install a service and enable it.  
For that, we'll want to deploy a full policy.  You guessed it, in our next module we'll do just that! 
