= Security and Compliance in an Image Mode world.

Building and Deploying using Image Mode has some built-in benefits from a security and compliance perspective.  First, systems deployed with Image Mode are more likely to be built to your desired specifications, and second it is much easier to make sure that they stay that way.  In the next few modules we'll walk through how to add security and compliance into your build, and also how to apply that policy using automation.  We will also touch a bit on drift and getting your systems back into compliance after an event.

== Adding a security control to your image FAPolicyd

A common service that helps you meet your security and compliance mandates, is FAPolicyd.  The File Access Policy Daemon is a service that implements application allow-listing.  So let's see what it looks like to simply add it to our `Containerfile`.  

** _NOTE_: We will be adding these changes after the Maintainer metadata line that was added earlier in our Containerfile so, after the "LABEL vendor="Example Corp" line, we'll add the following

[source,bash,role="execute",subs=attributes+]
----
# Security and Hardening 

RUN dnf -y install fapolicyd

RUN systemctl enable fapolicyd
----

== Build and Push

Now, if we build the image and push it, we can deploy and see if FAPolicyD is working.

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----
[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

If we head over to our bootc host, we can pull in the update, and reboot in order to see our changes. 

[source,bash,role="execute",subs=attributes+]
----
sudo bootc update --apply
----


