== Installing troublsehooting tools
It happens, we know.  Sometimes you need to install a package temporarility for some purpose.  Maybe it's troubleshooting, or gathering information for a support request, or just to carry out some task on your servers.  In RHEL package mode this is simple, you do a dnf install, and you're done. This however introduces drift.  It can also be a concern from a sercurity and compliance perspective. 

Imagine it, you're asked to get a packet capture to troubleshoot some network latency issue.  So you install tcpdump, and do your work.  Did you remember to remove it afterword?  Or another example, you install netcat to test some firewall ports, and then there it is, ready for an attacker to leverage for a reverse shell.  These are core examples of why package drift can be a bad thing.  Luckily RHEL Image Mode helps you control package drift by moving package installs into your image creation. 

There still might be a time where you'll need tcpdump or netcat though.  Should you add those to your bootc image?  No!  You'll install them transiently, and then they will go away on their own the next time the system is imaged, updated, or even rebooted. 

== Transient package installs

Let's say you needed to install netcat, like in my example above.

[source,bash,role="execute",subs=attributes+]
----
sudo dnf -y install netcat
----
A standard dnf install will result in an error:
....
This bootc system is configured to be read-only. Pass --transient to perform this transaction in a transient overlay which will reset when the system reboots.
Operation aborted.
....

There is a special flag that tells dnf to install a transient package, which works great with an immutable OS. 

[source,bash,role="execute",subs=attributes+]
----
sudo dnf -y install --transient netcat
----
Now you can reverse-shell all day long if you'd like. 

Troubleshooting can sometimes be chaoitic, and you're installing tools to help you gather your data.  It can be difficult to keep track of, and then remove all of those packages when you're done.  With a transient package though, all it takes is a reboot, and the package is gone. 

[source,bash,role="execute",subs=attributes+]
----
nc --help
----
Now you see it. 

[source,bash,role="execute",subs=attributes+]
----
sudo reboot
----

** _NOTE_: Rebooting will disconnect your tab from the security-vm system, simply press the 'reconnect' button in the center of the terminal to re-establish your session

After the system is rebooted, you can try to run netcat all you'd like, it's gone. 

[source,bash,role="execute",subs=attributes+]
----
nc -l 4242 | /bin/bash
----
Now you don't
....
[core@localhost ~]$ nc -l 4242 | /bin/bash
-bash: nc: command not found
[core@localhost ~]$ 
....


