= Building your own base images

There are times that you want to create your own bases from scratch instead of relying on the Red Hat base images. Here's how to do that.

[#write-containerfiles]
== Building from scratch
_Return to the "Build host" and change to a new directory for this exercise_
[source,bash,role="execute",subs=attributes+]
----
cd ~/scratch
----

Just like any other container image, bootc images can start from an empty filesystem called https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html/using_image_mode_for_rhel_to_build_deploy_and_manage_operating_systems/generating-a-custom-minimal-base-image[a "scratch image",window=_blank]. 
Some use cases may find this provides more control over available packages and may provide a smaller end image.

To create an image from scratch, use the Red Hat base as the builder, since the tools needed to create a rootfs that bootc can use are built into `bootc`.
This image will act as a new base image for later builds.

The documentation example is a multi-stage build that takes the components created by the `bootc` tooling as the starting point for the `scratch` image.
Instead, let's build a miminal base image to compare against the Red Hat base we've been using so far.

CAUTION: We've identified a bug in the latest minimal manifest that breaks `subscription-manager` using host entitlements in a containerized build. A workaround at the time of writing was only show effective for hosts using the CDN not Satellite, which is in use in this environment. For that reason, we'll use Fedora for this and following exercises.

We provide a minimal manifest that has even fewer packages selected. 
[source,bash,role="execute",subs=attributes+]
----
nano Containerfile.scratch
----

Copy the following Containerfile and save it.
[source,dockerfile,role="execute",subs=attributes+]
----
FROM quay.io/fedora/fedora-bootc:latest AS builder
# Build the root file system by using the specified repositories and non-RPM content from the "builder" base image.
RUN /usr/libexec/bootc-base-imagectl build-rootfs --manifest=minimal /target-rootfs <.>

# Create a new, empty image from scratch.
FROM scratch <.>
COPY --from=builder /target-rootfs/ /   <.>

# Define required labels for this bootc image to be recognized as such. <.>
LABEL containers.bootc 1
LABEL ostree.bootable 1

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

RUN bootc container lint

----
<.> `bootc` creates the image based on the specified manifest
<.> The special FROM statement that creates an empty image
<.> Moving the filesystem created in the builder image to the empty target
<.> Housekeeping to appropriately identitfy this as a `bootc` image to container tools


The definitions of base images are part of the https://gitlab.com/fedora/bootc/base-images[upstream project,window=_blank].
These manifests not only define the starting set of packages installed, but also system configuration for image mode support.

Similar to `bootc-image-builder`, to build a `scratch` image with `podman` we need to add additional capabilities and devices to the build, even as root.
[source,bash,role="execute",subs=attributes+]
----
podman build -t minimal -f Containerfile.scratch --cap-add=all --security-opt=label=type:container_runtime_t --device /dev/fuse
----

You can see that seemingly simple builder image does a huge amount of work setting up the base filesystem.

[source,bash,role="execute",subs=attributes+]
----
podman images minimal 
----
....
REPOSITORY         TAG         IMAGE ID      CREATED             SIZE
localhost/minimal  latest      4fff772a5913  2 minutes ago  738 MB
....

[source,bash,role="execute",subs=attributes+]
----
podman images quay.io/fedora/fedora-bootc:latest
----
....
REPOSITORY                            TAG         IMAGE ID      CREATED       SIZE
quay.io/fedora/fedora-bootc  latest      e96ee34fce43  9 hours ago  1.88 GB
....
You can see there's a significant size difference as the _minimal_ manifest only installed about 200 packages.
The standard Fedora base is about 500.

To see how these compare when put to actual use, let's build two new images from the same Containerfile using each base image.

[source,bash,role="execute",subs=attributes+]
----
nano Containerfile.std
----

For simplicity, we'll create a basic webserver image.
[source,dockerfile,role="execute",subs=attributes+]
----
# Begin with a standard bootc base image
FROM quay.io/fedora/fedora-bootc:latest

RUN dnf -y install httpd sudo
RUN dnf clean all
RUN rm /var/{log,cache,lib}/* -rf

RUN systemctl enable httpd
RUN echo "%wheel  ALL=(ALL)   NOPASSWD: ALL" >> /etc/sudoers.d/wheel
RUN bootc container lint
----

[source,bash,role="execute",subs=attributes+]
----
podman build -t httpd:base -f Containerfile.std
----

Now do the same for the freshly built minimal base image.
[source,bash,role="execute",subs=attributes+]
----
nano Containerfile.min
----

For simplicity, we'll create a basic webserver image.
[source,dockerfile,role="execute",subs=attributes+]
----
# Begin with a standard bootc base image
FROM localhost/minimal

RUN dnf -y install httpd sudo
RUN dnf clean all
RUN rm /var/{log,cache,lib}/* -rf

RUN systemctl enable httpddnf group list
RUN echo "%wheel  ALL=(ALL)   NOPASSWD: ALL" >> /etc/sudoers.d/wheel
RUN bootc container lint
----

[source,bash,role="execute",subs=attributes+]
----
podman build -t httpd:min -f Containerfile.min
----

Compare the sizes of our two httpd images
[source,bash,role="execute",subs=attributes+]
----
podman images httpd
----
....
REPOSITORY       TAG         IMAGE ID      CREATED         SIZE
localhost/httpd  min         05fd59cc6e7d  11 seconds ago  767 MB
localhost/httpd  base        7092c8504861  57 seconds ago  1.71 GB
....

There's still a size difference between these images, but we may be missing certain expected functionality.

[source,bash,role="execute",subs=attributes+]
----
podman run --rm -it httpd:base rpm -q openssh
----
....
openssh-10.0p1-6.fc43.x86_64
....

[source,bash,role="execute",subs=attributes+]
----
podman run --rm -it httpd:min rpm -q openssh
----
....
package openssh is not installed
....

The minimal profile is just that, minimal. 
The end user is responsible for adding packages to satisfy their requirements.
This smaller size is a trade off for more potential work identifying dependencies.

We could also skip the base image creation and use the minimal manifest directly by passing `--install` to the `bootc-base-imagectl` command.
Let's build a version of our `httpd` image that way and compare.

[source,bash,role="execute",subs=attributes+]
----
nano Containerfile.direct
----

[source,dockerfile,role="execute",subs=attributes+]
----
FROM quay.io/fedora/fedora-bootc:latest AS builder
# Build the root file system by using the specified repositories and non-RPM content from the "builder" base image.
RUN /usr/libexec/bootc-base-imagectl build-rootfs \
--install httpd \
--install sudo \
--manifest=minimal /target-rootfs <.>

# Create a new, empty image from scratch.
FROM scratch <.>
COPY --from=builder /target-rootfs/ /   <.>

RUN systemctl enable httpd
RUN echo "%wheel  ALL=(ALL)   NOPASSWD: ALL" >> /etc/sudoers.d/wheel

# Define required labels for this bootc image to be recognized as such. <.>
LABEL containers.bootc 1
LABEL ostree.bootable 1

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

RUN bootc container lint
----

Build the new image, again adding the additional capabilities required for the rootfs creation tasks.
[source,bash,role="execute",subs=attributes+]
----
podman build -t httpd:direct -f Containerfile.direct --cap-add=all --security-opt=label=type:container_runtime_t --device /dev/fuse
----

We've saved some space and don't need to worry about the derived build chain. 
This could be a viable option depending on the use case.
[source,bash,role="execute",subs=attributes+]
----
podman images httpd
----
....
localhost/httpd  direct      6fba52c29a66  21 seconds ago  750 MB
localhost/httpd  min         cd888ed9a49f  12 minutes ago  941 MB
localhost/httpd  base        3e96d3cf1e3c  14 minutes ago  2.03 GB
....
