= Build a bootc image
In this exercise, you will see how to apply application container build concepts to a bootc image.

The fundamental principle of image mode is applying a decade of container expertice and advancements to building operating system images.
This simple idea has a wide impact on how we think about OS design, working with 'gold images', working with other teams, addressing updates, and more.
In this lab, we'll walk through the process of creating a new 'gold image' for an application.
We'll start with the tools the operations team needs, add the requirements from the security team, and then get our applicaion ready for deployment.
[#write]
== Create the Containerfile

[NOTE]
====
The instructions will reflect `nano` commands.

In `nano`, you can save and exit with `Ctrl+x`, followed by the key `y` at the "Save modified buffer?" prompt 
and the `Enter` key at the prompt to keep the filename.

The `vim` editor is also available. Users of `vim` should already know the basics
of opening, saving and exiting the editor. 
====

Image mode hosts start with a standard Containerfile and the standard instructions. 
The `FROM` line defines the starting point of the build. 
We'll start with the base image published by Red Hat and add components from there.

Adding software from a RHEL repo looks the same as any other `dnf` command, wrapped in the `RUN` directive.
Like other containers, subscription information is taken from the build host by default, so there's no additional subscription management needed here to get access.

For our admins, we've got a list of common tools we need available on every host to integrate with the management and monitoring tools.
Let's add some common tools now, PCP, remote syslogging, kernel tuning, and `tumux`.
`RUN` directives act like shell commands, so this looks like any other command spread over multiple lines for readability.

First, let's create a directory tree that we will base all of our work out of. This is where all of our configuration and the `Containerfile` will live. 

[source,bash,role="execute",subs=attributes+]
----
mkdir ~/bootc-base
----

Now, inside of this base directory, we'll create a tree where our other confiration files will live as we build out our base image.

[source,bash,role="execute",subs=attributes+]
----
mkdir -p ~/bootc-base/etc/sudoers.d
----
[source,bash,role="execute",subs=attributes+]
----
mkdir -p ~/bootc-base/etc/ostree
----
[source,bash,role="execute",subs=attributes+]
----
mkdir -p ~/bootc-base/usr/lib/bootc/kargs.d
----

From here on, work done on our build host will be done within this base directory. So let's switch to it now. 

[source,bash,role="execute",subs=attributes+]
----
cd ~/bootc-base
----

Now, we can start creating our `Containerfile`.

[source,bash,role="execute",subs=attributes+]
----
nano Containerfile
----

[source,dockerfile,role="execute",subs=attributes+]
----
FROM registry.redhat.io/rhel10/rhel-bootc:10.1

RUN dnf -y install pcp-zeroconf \
        rsyslog \
        tmux \
        tuned
----

Some tools we need may come from 3rd party repositories, either community or project repos like `EPEL` or repos you maintain for your own applications.
Repos can be added directly to the image instead of the build host, allowing us better control over software available.
Install the `EPEL` repo RPM, and 2 additional admin favorites.
[source,dockerfile,role="execute",subs=attributes+]
----
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

RUN dnf -y install btop iftop
----

We can also add in the directory structures from above, so that future updates to etc, and usr, will be automatically added when we rebuild the image. 

[source,dockerfile,role="execute",subs=attributes+]
----
COPY etc/ /etc
COPY usr/ /usr
----

At this point you can save and exit your editor.  

[#registry authentication]
== Authenticating to a registry
Container images commonly live in a container registry.  In the majority of cases this is also true for Image Mode images, because they are OCI compliant container images, they just contain the added bits required to be bootable.  

Many times an enterprise registry will also require authentication.  In this lab, we have setup a registry as well, and it does require authentication.  

We can log in and cache credentials in our shell, but that won't work for the image mode hosts.

[source,bash,role="execute",subs=attributes+]
----
podman login -u core -p redhat registry-{guid}.{domain}
----

To create system credentials, we'll reuse the user login, but typically some sort of service acccount would be used.

In any case, the authentication files are identeical, and can be published in the image. This will allow a newly created image mode host to update immediately after install, because it already has cached registry credentials.

When you interactively login using `podman login`, your registry credendials are stored on disk, but the `podman login` command can also generate a file for a single registry. 

This can be useful as users may have personal credentials for a number of different registries and we don't want to accidentally include or leak these into different environments.
[source,bash,role="execute",subs=attributes+]
----
podman login -u core -p redhat registry-{guid}.{domain} --authfile=auth.json
----

And now we simply place it inside of the tree we created above. 

[source,bash,role="execute",subs=attributes+]
----
mv auth.json etc/ostree/auth.json
----

[#build]
== Build the first bootc image

As with application containers, you can build this container with standard tools:

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----
The arguments we pass to `podman` are:

  * `--file Containerfile` -> what Containerfile to use for the build
  * `--tag registry-{guid}.{domain}/base` -> the "tag" or name of the resulting container in the format
     <registry>/<repository>

You will see `podman` process each line of the Containerfile just as it would for an application container. Once complete, the last two lines of the output should read like this:

[source,subs=attributes+]
----
Successfully tagged registry-{guid}.{domain}/httpd
f1bea10eb37acf2e78a9b01c6242110c1901adbaf40dbce479241c6c735c58da
----

And now we can push this image to the tagged registry with:

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

You have now built your first complete RHEL image as a bootc image!
The standard Red Hat bootc base image includes not just the kernel, firmware, bootloader, and other tools not required for a traditional container, but also common other tools and dependencies like SSH, NetworkManager, and more.
This separates the bootc base image from other Red Hat provided images like UBI.

